version: '3.1'

services:
  couchdb:
    image: couchdb
    container_name: couchdb
    hostname: couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - "5984:5984"
